### ISSUE TITLE
sfdx deploy:aura does not work as expected for controller and helper .js files in AuraDefinitionBundle

### ISSUE THREAD

**Issue by jprichter** [msrivastav13/mo-dx-plugin#2]
First off, super stoked about this tool. I've used it to save apex classes and the .cmp part of an AuraDefinitionBundle and the saves are faster than a sfdx:force:source:push or the sfdx deploy with manifest by a long shot. 

However, when I try to save a controller or a helper .js file of an AuraDefinitionBundle, it shows that it saves in VSCode, but when I view the component in the Developer Console, the saves are not there.

**Comment by msrivastav13** [comment]
@jprichter Thanks for using this .Sometimes the dev console does not reflect even after the file is saved immediately .Its a bug in dev console . Couple of refresh should show it .

I have been using this myself and never came across the issue .Let me check once again and i would request you to also test few more .Thanks again and i look forward to resolving every issue .

**Comment by jprichter** [comment]
@msrivastav13 I've waited minutes, refreshed, even hard refreshed. Only the code in *.js files of an AuraDefinitionBundle is not saving. I'm using this against a trailhead playground and have not tried it against any other type of org.

**Comment by msrivastav13** [comment]
@jprichter Thank you .I see there is some issue for sure .Thanks for bringing it up .Are you using this from the vscode plugin or from command line ?

**Comment by jprichter** [comment]
Glad you were able to reproduce it. I use the plugin, but I tested from the cli as well.

**Comment by msrivastav13** [comment]
@jprichter I have patched the bug . You should be able to get the latest plugin by running `sfdx plugins:update` .Let me know if you see further issues or anything you think will be useful to have in the project .

**Comment by jprichter** [comment]
Thanks!
