### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by jonnypetraglia** [msrivastav13/mo-dx-plugin#315]
Hey! Thanks for the awesome plugin, our team LOVES it!

It says the License is MIT in package.json but there's no License file. I was going to put it in a PR for you but then I realized I don't know who to set as the Copyright holder.

**Comment by msrivastav13** [comment]
Please put in Mohith Shrivastava as the copywrite holder.

Will accept the PR and also bump the npm libraries in next release.

Thank you
