### ISSUE TITLE
Issue while saving LWC Js-meta.xml file

### ISSUE THREAD

**Issue by guhaanandhnec08** [msrivastav13/mo-dx-plugin#4]
I created an LWC component and tried enabling it for all lightning pages through the <Target> attribute as shown below. 

`<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata" fqn="demo1">
    <apiVersion>45.0</apiVersion>
    <isExposed>true</isExposed>
    <targets>
        <target>lightning__AppPage</target>
        <target>lightning__RecordPage</target>
        <target>lightning__HomePage</target>
    </targets>
</LightningComponentBundle>`

But seems like this file is not properly deploying to the org although the status of the save says deployed. The LWC was not visible in the Lightning App Builder after deploying. 

Then I tried with SFDX: Deploy Source to Org then it started appearing in the App builder page.

**Comment by msrivastav13** [comment]
Currently salesforce is not supporting xml updates for lwc using tooling api so till then workaround for this is use native SFDX deploy command for first time .
